name: SMW Mediawiki Image Build

on:
  push:
    branches:
      - 'smw'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set Calver Version
        uses: Nelyx/action-calver@v1.0.0
        id: setcalver
        with:
          default_branch: 'refs/heads/smw'
          format: 'YY.MM.DD'
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: starcitizentools/mediawiki:smw-latest,starcitizentools/mediawiki:smw-${{ steps.setcalver.outputs.package_version }}
